<?php

namespace AD\LearningBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AD\LearningBundle\Entity\Course;

/**
 * courseModuleLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseModuleLinkRepository extends EntityRepository {

    public function findAllModulesByCourse(Course $course) {
        $sql = 'SELECT m'
                . ' FROM ADLearningBundle:Module m'
                . ' JOIN ADLearningBundle:CourseModuleLink l'
                . ' WHERE l.module = m'
                . ' JOIN ADLearningBundle:Course c'
                . ' WHERE l.course = c'
                . ' AND c = :course';

        $query = $this->getEntityManager()->createQuery($sql)->setParameter('course', $course);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
