services:
    
    ad_learning.beta.html:
        class: AD\LearningBundle\Beta\BetaHTML
    
    ad_learning.beta.listener:
        class: AD\LearningBundle\Beta\BetaListener
        arguments: [@ad_learning.beta.html, "2017-05-19"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }
