#ad_user:
#    resource: "@ADUserBundle/Resources/config/routing.yml"
#ß    prefix:   /

ad_learning:
    resource: "@ADLearningBundle/Resources/config/routing.yml"
    prefix:   /
    
admin:
    resource: "@ADAdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
login: 
    pattern: /login
    defaults: {_controller: ADUserBundle:Security:login }
    
login_check:
    pattern: /login_check

logout:
    pattern: /logout

